# -*- coding: utf-8 -*-
"""Pipeline GEIH — Notebook ejecutable.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlnDv9uXcOYWYRaSyZ6xfKKrB9PWvf8_

Autor: Néstor Enrique Forero Herrera
Paquete: geih v4.1.0 — 57 clases de análisis
Guía metodológica completa: GUIA_GEIH.md (en la carpeta del paquete)

Autor: Néstor Enrique Forero Herrera de Datos
"""

# ══════════════════════════════════════════════════════════════════════
# CELDA 1 · Montar Drive + cargar paquete
# ══════════════════════════════════════════════════════════════════════

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.insert(0, '/content/drive/MyDrive/GEIH'  # ← ajustar a tu ruta)

from geih import __version__
print(f"✅ geih v{__version__} — 57 clases de análisis cargadas")

# ══════════════════════════════════════════════════════════════════════
# CELDA 2 · Configuración (ÚNICO LUGAR DONDE SE CAMBIAN PARÁMETROS)
# ══════════════════════════════════════════════════════════════════════

from geih import ConfigGEIH

# ┌──────────────────────────────────────────────────────────────────┐
# │  PARÁMETROS DEL USUARIO — Modificar aquí para cada corrida      │
# │  anio    : Año de los datos (2025, 2026, ...)                   │
# │  n_meses : Cuántos meses consolidar (1-12)                     │
# │  Para mes puntual: n_meses=1, mes_filtro=N en preparar_base()  │
# └──────────────────────────────────────────────────────────────────┘
ANIO    = 2025
N_MESES = 12

RUTA          = '/content/drive/MyDrive/GEIH'  # ← ajustar a tu ruta
RUTA_CIIU     = '/content/drive/MyDrive/ProColombia/0A. Datos/Correlativas/2025-01-14 Correlativa CIIU Rev4 - Cadenas ProColombia.xlsx'
RUTA_DIVIPOLA = '/content/drive/MyDrive/ProColombia/0A. Datos/Correlativas/2025-01-14 DIVIPOLA.xlsx'

config = ConfigGEIH(anio=ANIO, n_meses=N_MESES)
config.resumen()

# ══════════════════════════════════════════════════════════════════════
# CELDA 3 · Consolidar (primera vez) o cargar Parquet existente
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import ConsolidadorGEIH, GestorMemoria
import os

PARQUET = f'{RUTA}/GEIH_{ANIO}_Consolidado.parquet'

if os.path.exists(PARQUET):
    print(f"📂 Cargando base existente: {PARQUET}")
    geih = ConsolidadorGEIH.cargar(PARQUET)
else:
    print(f"🔄 Consolidando {N_MESES} meses de {ANIO}...")
    consolidador = ConsolidadorGEIH(ruta_base=RUTA, config=config, incluir_area=True)
    consolidador.verificar_estructura()
    geih = consolidador.consolidar()
    consolidador.exportar(geih)

GestorMemoria.estado()

# ══════════════════════════════════════════════════════════════════════
# CELDA 4 · Diagnóstico rápido + validación de identidades
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import DiagnosticoCalidad

diag = DiagnosticoCalidad()
diag.resumen_rapido(geih)
diag.verificar_tipos(geih)
diag.validar_identidades(geih)

# ══════════════════════════════════════════════════════════════════════
# CELDA 5 · Preparar datos (FEX_ADJ + variables derivadas)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import PreparadorGEIH, Exportador

prep = PreparadorGEIH(config=config)
df = prep.preparar_base(geih)
df = prep.agregar_variables_derivadas(df)

exp = Exportador(ruta_base=RUTA, config=config)
print(f"✅ df preparado: {df.shape[0]:,} filas × {df.shape[1]} columnas")

# ══════════════════════════════════════════════════════════════════════
# CELDA 6 · Indicadores nacionales + sanity check
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import IndicadoresLaborales

ind = IndicadoresLaborales(config=config)
r = ind.calcular(df)
ind.sanity_check(r, f"Anual {ANIO}")
td_dpto = ind.por_departamento(df)
exp.guardar_tabla(td_dpto, f'M0_indicadores_departamento_{ANIO}')

# ══════════════════════════════════════════════════════════════════════
# CELDA 7 · 10 análisis básicos (M1–M6, M11, M12, Mincer, Gini)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import (
    DistribucionIngresos, AnalisisRamaSexo, AnalisisSalarios,
    BrechaGenero, IndicesCompuestos, Estacionalidad,
    AnalisisUrbanoRural, FuerzaLaboralJoven, EcuacionMincer,
)
from geih import Top20Sectores

print(f"\n{'='*60}")
print(f"  10 ANÁLISIS BÁSICOS — {config.periodo_etiqueta}")
print(f"{'='*60}")

dist_ing = DistribucionIngresos(config=config).calcular(df)
exp.guardar_tabla(dist_ing['total'], f'M1_distribucion_ingresos_{ANIO}')

rama_sexo = AnalisisRamaSexo().calcular(df)
exp.guardar_tabla(rama_sexo, f'M3_rama_sexo_{ANIO}')

salarios_rama = AnalisisSalarios(config=config).por_rama(df)
exp.guardar_tabla(salarios_rama.reset_index(), f'M4_salarios_rama_{ANIO}')

brecha = BrechaGenero().calcular(df)
exp.guardar_tabla(brecha.reset_index(), f'M6_brecha_genero_{ANIO}')

gini_val = IndicesCompuestos(config=config).gini(df)
print(f"\n  Gini del ingreso laboral: {gini_val:.3f}")

estac = Estacionalidad().calcular(geih)
exp.guardar_tabla(estac, f'M11_estacionalidad_{ANIO}')

urb_rural = AnalisisUrbanoRural(config=config).calcular(df)
exp.guardar_tabla(urb_rural, f'M_urbano_rural_{ANIO}')

joven = FuerzaLaboralJoven(config=config).calcular(df)
exp.guardar_tabla(joven, f'M12_fuerza_laboral_joven_{ANIO}')

mincer = EcuacionMincer(config=config).estimar_todos(df)
exp.guardar_tabla(mincer, f'MC_mincer_{ANIO}')

top20 = Top20Sectores(config=config).calcular(df, ruta_ciiu=RUTA_CIIU)
exp.guardar_tabla(top20, f'Top20_sectores_CIIU_{ANIO}')

print(f"\n✅ 10 análisis básicos completados")

# ══════════════════════════════════════════════════════════════════════
# CELDA 8 · 8 análisis avanzados (ICE, ICF, ICI, IVI, ITAT, etc.)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import (
    CalidadEmpleo, FormalidadSectorial, CompetitividadLaboral,
    VulnerabilidadLaboral, CostoLaboral, ContribucionSectorial,
    MapaTalento, BonoDemografico,
)

print(f"\n{'='*60}")
print(f"  8 ANÁLISIS AVANZADOS — {config.periodo_etiqueta}")
print(f"{'='*60}")

ice_dpto = CalidadEmpleo(config=config).calcular_por_departamento(df)
exp.guardar_tabla(ice_dpto, f'M7_ICE_departamento_{ANIO}')

icf = FormalidadSectorial(config=config).calcular(df)
exp.guardar_tabla(icf, f'M13_formalidad_sectorial_{ANIO}')

ici = CompetitividadLaboral(config=config).calcular(df)
exp.guardar_tabla(ici, f'M16_ICI_competitividad_{ANIO}')

ivi = VulnerabilidadLaboral(config=config).calcular(df)
exp.guardar_tabla(ivi, f'M20_vulnerabilidad_{ANIO}')

costo = CostoLaboral(config=config).calcular(df)
exp.guardar_tabla(costo, f'M19_costo_laboral_{ANIO}')

contrib = ContribucionSectorial().calcular(geih)
exp.guardar_tabla(contrib, f'MA_contribucion_sectorial_{ANIO}')

talento = MapaTalento(config=config).calcular(df)
exp.guardar_tabla(talento, f'MB_mapa_talento_ITAT_{ANIO}')

bono = BonoDemografico(config=config).calcular(df)
exp.guardar_tabla(bono, f'M18_bono_demografico_{ANIO}')

print(f"\n✅ 8 análisis avanzados completados")

# ══════════════════════════════════════════════════════════════════════
# CELDA 9 · 10 análisis poblacionales + 5 complementarios
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import (
    AnalisisCampesino, AnalisisDiscapacidad, AnalisisMigracion,
    AnalisisOtrasFormas, AnalisisOtrosIngresos, AnalisisSobrecalificacion,
    AnalisisContractual, AnalisisAutonomia, AnalisisAlcanceMercado,
    AnalisisDesanimados,
    DuracionDesempleo, DashboardSectoresProColombia,
    AnatomaSalario, FormaPago, CanalEmpleo,
)

print(f"\n{'='*60}")
print(f"  15 ANÁLISIS POBLACIONALES — {config.periodo_etiqueta}")
print(f"{'='*60}")

resultados_pob = {
    'Campesino':        AnalisisCampesino(config=config).calcular(df),
    'Discapacidad':     AnalisisDiscapacidad().calcular(df),
    'Migracion':        AnalisisMigracion(config=config).calcular(df),
    'Otras_formas':     AnalisisOtrasFormas().calcular(df),
    'Otros_ingresos':   AnalisisOtrosIngresos().calcular(df),
    'Sobrecalificacion':AnalisisSobrecalificacion().calcular(df),
    'Contractual':      AnalisisContractual().calcular(df),
    'Autonomia':        AnalisisAutonomia().calcular(df),
    'Alcance_mercado':  AnalisisAlcanceMercado().calcular(df),
    'Desanimados':      AnalisisDesanimados().calcular(df),
    'M8_Duracion':      DuracionDesempleo(config=config).calcular(df),
    'M14_Dashboard':    DashboardSectoresProColombia(config=config).calcular(df),
    'MX2_Forma_pago':   FormaPago(config=config).calcular(df),
    'MX3_Canal_empleo': CanalEmpleo(config=config).calcular(df),
}

for nombre, tabla in resultados_pob.items():
    if tabla is not None and len(tabla) > 0:
        exp.guardar_tabla(tabla, f'{nombre}_{ANIO}')

anat = AnatomaSalario(config=config)
anat.resumen_nacional(df)
anat_rama = anat.por_rama(df)
if len(anat_rama) > 0:
    exp.guardar_tabla(anat_rama, f'MX1_anatomia_salario_{ANIO}')

dur_dpto = DuracionDesempleo(config=config).por_departamento(df)
if len(dur_dpto) > 0:
    exp.guardar_tabla(dur_dpto, f'M8_rigidez_departamental_{ANIO}')

print(f"\n✅ 15 análisis poblacionales completados")

# ══════════════════════════════════════════════════════════════════════
# CELDA 10 · Histogramas horas/ingresos (matplotlib + plotly)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import gc

FONDO = '#F7F9FC'
C = {'azul':'#2E6DA4','rojo':'#C0392B','verde':'#1E8449',
     'morado':'#7D3C98','naranja':'#E67E22','gris':'#7F8C8D',
     'amarillo':'#F39C12'}
SMMLV = config.smmlv

df_hist_ocu = df[df['OCI'] == 1].copy()
print(f"Ocupados para histogramas: {len(df_hist_ocu):,} registros")

fig_h = plt.figure(figsize=(18, 10))
fig_h.patch.set_facecolor(FONDO)
gs_h = plt.GridSpec(2, 3, figure=fig_h, hspace=0.45, wspace=0.38)
ax_h1 = fig_h.add_subplot(gs_h[0, :2])
ax_h2 = fig_h.add_subplot(gs_h[0, 2])
ax_h3 = fig_h.add_subplot(gs_h[1, :2])
ax_h4 = fig_h.add_subplot(gs_h[1, 2])
for ax in [ax_h1, ax_h2, ax_h3, ax_h4]:
    ax.set_facecolor('white'); ax.spines[['top','right']].set_visible(False)

if 'P6800' in df_hist_ocu.columns:
    df_p68 = df_hist_ocu[df_hist_ocu['P6800'].between(1, 100)].copy()
    bins_h = np.arange(0, 101, 4)
    counts_h, edges_h = np.histogram(df_p68['P6800'], bins=bins_h, weights=df_p68['FEX_ADJ'])
    ax_h1.bar(edges_h[:-1], counts_h/1e6, width=3.8, color=C['azul'], alpha=0.82, align='edge')
    for horas, label, col_v in [(40,'40h legal',C['verde']),(48,'48h límite',C['naranja']),(32,'32h subempleo',C['rojo'])]:
        ax_h1.axvline(horas, color=col_v, ls='--', lw=1.8, alpha=0.85)
        ax_h1.text(horas+0.3, counts_h.max()/1e6*0.85, label, fontsize=8, color=col_v, fontweight='bold')
    v8, w8 = df_p68['P6800'].values, df_p68['FEX_ADJ'].values
    idx8 = np.argsort(v8); v8, w8 = v8[idx8], w8[idx8]
    med8 = float(v8[np.searchsorted(np.cumsum(w8), np.cumsum(w8)[-1]/2)])
    ax_h1.axvline(med8, color='black', ls='-', lw=2, alpha=0.7)
    ax_h1.text(med8+0.5, counts_h.max()/1e6*1.02, f'Mediana={med8:.0f}h', fontsize=9, fontweight='bold')
    ax_h1.set_xlabel('Horas normales semanales (P6800)'); ax_h1.set_ylabel('Personas (millones)')
    ax_h1.set_title(f'Distribución de horas normales — GEIH {ANIO}', fontsize=11, fontweight='bold')
    ax_h1.grid(axis='y', alpha=0.3)

    BINS_LABS = [(1,15,'<15h'),(15,32,'15–32h'),(32,40,'32–40h'),(40,48,'40–48h'),(48,70,'48–70h'),(70,126,'>70h')]
    vals_bins = [df_p68.loc[df_p68['P6800'].between(lo, hi), 'FEX_ADJ'].sum()/1e6 for lo,hi,_ in BINS_LABS]
    col_bins = [C['rojo'],C['naranja'],C['amarillo'],C['verde'],C['naranja'],C['rojo']]
    bars_h2 = ax_h2.bar(range(len(vals_bins)), vals_bins, 0.7, color=col_bins, alpha=0.85)
    for bar, v in zip(bars_h2, vals_bins):
        ax_h2.text(bar.get_x()+bar.get_width()/2, v+0.03, f'{v:.2f}M', ha='center', fontsize=8.5, fontweight='bold')
    ax_h2.set_xticks(range(len(BINS_LABS))); ax_h2.set_xticklabels([l for _,_,l in BINS_LABS], fontsize=8)
    ax_h2.set_ylabel('Millones'); ax_h2.set_title('Por rango de horas', fontsize=10, fontweight='bold')
    ax_h2.grid(axis='y', alpha=0.3)

if 'P6850' in df_hist_ocu.columns:
    df_p685 = df_hist_ocu[df_hist_ocu['P6850'].between(1, 100)].copy()
    for sx_v, sx_l, col_s in [(1,'Hombres',C['azul']),(2,'Mujeres',C['rojo'])]:
        sub = df_p685[df_p685['P3271'] == sx_v]
        if len(sub) == 0: continue
        counts_s, _ = np.histogram(sub['P6850'], bins=bins_h, weights=sub['FEX_ADJ'])
        ax_h3.plot(edges_h[:-1]+2, counts_s/1e6, lw=2.2, color=col_s, label=sx_l, alpha=0.88)
        ax_h3.fill_between(edges_h[:-1]+2, counts_s/1e6, alpha=0.12, color=col_s)
    ax_h3.axvline(48, color=C['naranja'], ls='--', lw=1.5, alpha=0.7, label='48h')
    ax_h3.set_xlabel('Horas reales (P6850)'); ax_h3.set_ylabel('Personas (millones)')
    ax_h3.set_title(f'Horas reales por sexo — GEIH {ANIO}', fontsize=11, fontweight='bold')
    ax_h3.legend(fontsize=10); ax_h3.grid(axis='y', alpha=0.3)

if 'P6800' in df_hist_ocu.columns and 'INGLABO' in df_hist_ocu.columns:
    df_sc = df_hist_ocu[df_hist_ocu['P6800'].between(1,80) & df_hist_ocu['INGLABO'].between(100_000, 15_000_000)]
    if len(df_sc) > 0:
        df_sc_s = df_sc.sample(min(5000, len(df_sc)), weights='FEX_ADJ', random_state=42, replace=True)
        ax_h4.scatter(df_sc_s['P6800'], df_sc_s['INGLABO']/SMMLV, alpha=0.08, s=8, color=C['azul'])
        ax_h4.axhline(1, color=C['verde'], ls='--', lw=1.3, alpha=0.7)
        ax_h4.set_xlabel('Horas semanales'); ax_h4.set_ylabel('Ingreso (× SMMLV)')
        ax_h4.set_title('Horas vs ingreso (5K muestra)', fontsize=10, fontweight='bold')
        ax_h4.set_ylim(0, 12); ax_h4.grid(alpha=0.2)

fig_h.suptitle(f'ANÁLISIS DE HORAS TRABAJADAS — GEIH {ANIO}', fontsize=13, fontweight='bold')
plt.tight_layout(rect=[0, 0, 1, 0.94]); plt.show()
exp.guardar_grafica(fig_h, f'Histograma_horas_{ANIO}', cerrar=True)

try:
    import plotly.express as px
    df_plotly = df_hist_ocu[df_hist_ocu['INGLABO'].between(50_000, 20_000_000)].copy()
    df_plotly['INGLABO_SML'] = df_plotly['INGLABO'] / SMMLV
    df_plotly['SEXO'] = df_plotly['P3271'].map({1:'Hombres', 2:'Mujeres'})
    df_pl_s = df_plotly[df_plotly['SEXO'].notna()].sample(min(30_000, len(df_plotly)), weights='FEX_ADJ', random_state=42, replace=True)
    fig_px = px.box(df_pl_s, x='SEXO', y='INGLABO_SML', color='SEXO',
                    color_discrete_map={'Hombres':'#2E6DA4','Mujeres':'#C0392B'},
                    title=f'Distribución del ingreso laboral por sexo — GEIH {ANIO}',
                    labels={'INGLABO_SML':'Ingreso (× SMMLV)','SEXO':''}, points='outliers')
    fig_px.update_layout(yaxis=dict(range=[0,15]), plot_bgcolor='white', paper_bgcolor='#F7F9FC', showlegend=False)
    fig_px.add_hline(y=1, line_dash='dash', line_color='#1E8449', annotation_text='1 SMMLV')
    fig_px.show()
    print("✅ Box plot interactivo Plotly generado")
except ImportError:
    print("⚠️  plotly no disponible — instalar con: !pip install plotly")

del df_hist_ocu; gc.collect()
print("✅ Celda 10 completada")

# ══════════════════════════════════════════════════════════════════════
# CELDA 11 · Cruce empresa × departamento (P7130, P3069, P6920)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
import matplotlib.colors as mcolors
from geih import DEPARTAMENTOS, TAMANO_EMPRESA

df_ocu_cr = df[df['OCI'] == 1].copy()
if 'NOMBRE_DPTO' not in df_ocu_cr.columns:
    df_ocu_cr['DPTO_STR'] = df_ocu_cr['DPTO'].astype(str).str.zfill(2)
    df_ocu_cr['NOMBRE_DPTO'] = df_ocu_cr['DPTO_STR'].map(DEPARTAMENTOS)

filas_cr = []
for dpto_nom in df_ocu_cr['NOMBRE_DPTO'].dropna().unique():
    m_d = df_ocu_cr['NOMBRE_DPTO'] == dpto_nom
    n_tot = df_ocu_cr.loc[m_d, 'FEX_ADJ'].sum()
    if n_tot < 5_000: continue
    fila = {'Departamento': dpto_nom, 'Ocupados_M': round(n_tot/1e6, 2)}
    if 'P7130' in df_ocu_cr.columns:
        fila['Desea_cambiar_%'] = round(df_ocu_cr.loc[m_d & (df_ocu_cr['P7130']==1), 'FEX_ADJ'].sum() / n_tot * 100, 1)
    if 'P6920' in df_ocu_cr.columns:
        fila['Cotiza_pension_%'] = round(df_ocu_cr.loc[m_d & (df_ocu_cr['P6920']==1), 'FEX_ADJ'].sum() / n_tot * 100, 1)
    if 'P3069' in df_ocu_cr.columns:
        for cod_t, lab_t in TAMANO_EMPRESA.items():
            fila[f'Emp_{lab_t}'] = round(df_ocu_cr.loc[m_d & (df_ocu_cr['P3069']==cod_t), 'FEX_ADJ'].sum() / n_tot * 100, 1)
    filas_cr.append(fila)

df_cruce = pd.DataFrame(filas_cr)
if 'Desea_cambiar_%' in df_cruce.columns:
    df_cruce = df_cruce.sort_values('Desea_cambiar_%', ascending=False)

import pandas as pd
fig_cr, (ax_cr1, ax_cr2) = plt.subplots(1, 2, figsize=(18, 8))
fig_cr.patch.set_facecolor(FONDO); ax_cr1.set_facecolor('white'); ax_cr2.set_facecolor('white')

if 'Desea_cambiar_%' in df_cruce.columns:
    df_plot_cr = df_cruce.sort_values('Desea_cambiar_%', ascending=True)
    y_cr = np.arange(len(df_plot_cr))
    col_cr = [C['rojo'] if v > 40 else (C['naranja'] if v > 25 else C['verde']) for v in df_plot_cr['Desea_cambiar_%']]
    ax_cr1.barh(y_cr, df_plot_cr['Desea_cambiar_%'], 0.65, color=col_cr, alpha=0.88)
    prom = df_cruce['Desea_cambiar_%'].mean()
    ax_cr1.axvline(prom, color='gray', ls='--', lw=1.3, alpha=0.7, label=f'Promedio ({prom:.1f}%)')
    for i, (_, row) in enumerate(df_plot_cr.iterrows()):
        ax_cr1.text(row['Desea_cambiar_%']+0.3, i, f"{row['Desea_cambiar_%']:.1f}%", va='center', fontsize=8)
    ax_cr1.set_yticks(y_cr); ax_cr1.set_yticklabels(df_plot_cr['Departamento'], fontsize=9)
    ax_cr1.set_xlabel('% desea cambiar (P7130=1)'); ax_cr1.set_title(f'Insatisfacción laboral — GEIH {ANIO}', fontsize=11, fontweight='bold')
    ax_cr1.legend(fontsize=9); ax_cr1.grid(axis='x', alpha=0.3); ax_cr1.spines[['top','right']].set_visible(False)

cols_tam = [c for c in df_cruce.columns if c.startswith('Emp_')]
if cols_tam:
    df_hm = df_cruce.set_index('Departamento')[cols_tam].fillna(0)
    df_hm.columns = [c.replace('Emp_','') for c in df_hm.columns]
    cmap_t = mcolors.LinearSegmentedColormap.from_list('wg', ['white','#2E6DA4'])
    im_t = ax_cr2.imshow(df_hm.values, cmap=cmap_t, aspect='auto', vmin=0, vmax=50)
    plt.colorbar(im_t, ax=ax_cr2, label='% empleo')
    for i in range(len(df_hm)):
        for j in range(len(df_hm.columns)):
            v = df_hm.iloc[i,j]
            if v >= 5: ax_cr2.text(j, i, f'{v:.0f}%', ha='center', va='center', fontsize=7, fontweight='bold',
                                    color='white' if v > 30 else '#1A252F')
    ax_cr2.set_xticks(range(len(df_hm.columns))); ax_cr2.set_xticklabels(df_hm.columns, rotation=35, ha='right', fontsize=8)
    ax_cr2.set_yticks(range(len(df_hm))); ax_cr2.set_yticklabels(df_hm.index, fontsize=8)
    ax_cr2.set_title(f'Tamaño empresa × departamento — GEIH {ANIO}', fontsize=11, fontweight='bold')

fig_cr.suptitle(f'CRUCE EMPRESA × DEPARTAMENTO — GEIH {ANIO}', fontsize=13, fontweight='bold')
fig_cr.tight_layout(pad=2.5); plt.show()
exp.guardar_grafica(fig_cr, f'Cruce_empresa_dpto_{ANIO}', cerrar=True)
exp.guardar_tabla(df_cruce, f'Cruce_empresa_departamento_{ANIO}')
del df_ocu_cr; gc.collect()
print("✅ Celda 11 completada")

# ══════════════════════════════════════════════════════════════════════
# CELDA 12 · 4 gráficos avanzados (Lorenz, ICI bubble, estacionalidad, heatmap)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import (
    GraficoCurvaLorenz, GraficoICIBubble,
    GraficoEstacionalidad, GraficoContribucionHeatmap,
    GraficoBoxPlotSalarios, GraficoBrechaGenero,
)

df_ocu_lorenz = df[(df['OCI'] == 1) & (df['INGLABO'] > 0)]
fig_lorenz = GraficoCurvaLorenz().graficar(df_ocu_lorenz,
    titulo=f'Curva de Lorenz del ingreso laboral — GEIH {ANIO}')
exp.guardar_grafica(fig_lorenz, f'M5_Lorenz_Gini_{ANIO}')
plt.show()

if 'Costo_efectivo' in ici.columns and 'Talento_univ_%' in ici.columns:
    fig_ici = GraficoICIBubble().graficar(ici,
        titulo=f'Competitividad laboral (ICI) — GEIH {ANIO}')
    exp.guardar_grafica(fig_ici, f'M16_ICI_bubble_{ANIO}')
    plt.show()

fig_estac = GraficoEstacionalidad().graficar(estac,
    titulo=f'Estacionalidad del mercado laboral — GEIH {ANIO}')
exp.guardar_grafica(fig_estac, f'M11_Estacionalidad_lineas_{ANIO}')
plt.show()

fig_boxplot = GraficoBoxPlotSalarios().graficar(salarios_rama,
    titulo=f'Distribución del ingreso por rama — GEIH {ANIO}', smmlv=SMMLV)
exp.guardar_grafica(fig_boxplot, f'M4_BoxPlot_salarios_{ANIO}')
plt.show()

fig_brecha = GraficoBrechaGenero().graficar(brecha,
    titulo=f'Brecha salarial de género — GEIH {ANIO}', smmlv=SMMLV)
exp.guardar_grafica(fig_brecha, f'M6_Brecha_genero_{ANIO}')
plt.show()

plt.close('all')
gc.collect()
print("✅ Celda 12 completada — 5 gráficos generados")

# ══════════════════════════════════════════════════════════════════════
# CELDA 13 · Análisis por 32 ciudades (AREA)
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
from geih import AnalisisOcupadosCiudad

area = AnalisisOcupadosCiudad(config=config)
tablas_area = area.calcular_tablas(df)
area.exportar_excel(tablas_area, str(exp.excel / f'CIIU_Area_{ANIO}.xlsx'))
print("✅ Celda 13 completada — 6 tablas AREA exportadas")

# ══════════════════════════════════════════════════════════════════════
# CELDA 14 · Excel consolidado multi-hoja + metadata
# ══════════════════════════════════════════════════════════════════════

# Commented out IPython magic to ensure Python compatibility.
# %%time
print(f"\n📗 Exportando Excel consolidado con formato institucional ProColombia...")

exp.guardar_excel({
    'Indicadores_dpto':     td_dpto,
    'Salarios_rama':        salarios_rama.reset_index(),
    'Brecha_genero':        brecha.reset_index(),
    'ICE_departamento':     ice_dpto,
    'ICI_competitividad':   ici,
    'Formalidad_ICF':       icf,
    'Vulnerabilidad_IVI':   ivi,
    'Costo_laboral':        costo,
    'Bono_demografico':     bono,
    'Talento_ITAT':         talento,
    'Estacionalidad':       estac,
    'Joven_15_28':          joven,
    'Urbano_Rural':         urb_rural,
    'Mincer':               mincer,
    'Contribucion_sect':    contrib,
    'Top20_CIIU':           top20,
}, f'GEIH_{ANIO}_Analisis_Completo_ProColombia')

exp.guardar_metadata(config, {
    'n_registros': len(geih),
    'n_columnas': geih.shape[1],
    'meses_procesados': N_MESES,
    'anio': ANIO,
    'clases_ejecutadas': 57,
    'version_paquete': __version__,
})

exp.resumen()
print("✅ Celda 14 completada")

# ══════════════════════════════════════════════════════════════════════
# CELDA 15 · Resumen final + liberación de memoria
# ══════════════════════════════════════════════════════════════════════

print(f"\n{'='*65}")
print(f"  ✅ PIPELINE GEIH {ANIO} COMPLETADO")
print(f"{'='*65}")
print(f"  Período          : {config.periodo_etiqueta}")
print(f"  Base              : {geih.shape[0]:,} filas × {geih.shape[1]} cols")
print(f"  Análisis básicos  : 10 tablas")
print(f"  Análisis avanzados: 8 tablas")
print(f"  Análisis poblac.  : 15 tablas")
print(f"  Gráficos          : 7 PNGs")
print(f"  Excel             : 1 multi-hoja + 1 AREA")
print(f"  CSVs              : ver resultados_geih_{ANIO}/tablas/")
print(f"{'='*65}")

GestorMemoria.estado()

from datetime import datetime
import pytz
print(f"\n  Finalizado: {datetime.now(pytz.timezone('America/Bogota')).strftime('%Y-%m-%d %H:%M:%S')} (hora Colombia)")
